name: Release

on:
    push:
      tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: git-checkout
        uses: actions/checkout@v3
        with:
          node-version:  ${{matrix.node-version}}
        
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build

      - name: push
        uses: s0/git-publish-subdir-action@develop
        env: 
            REPO: self
            BRANCH: public
            FOLDER: public_temp
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            MESSAGE: "Build: {{sha}} {msg}"